CREATE DATABASE `bnkbase` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `bnkbase`;
CREATE TABLE `bnkbase`.`tb_pzn` (
  `VKEY` char(2) NOT NULL,
  `PZN` char(2) DEFAULT NULL,
  `IMY` char(4) DEFAULT NULL,
  `NAME` char(40) DEFAULT NULL,
  `CB_DATE` date DEFAULT NULL,
  `CE_DATE` date DEFAULT NULL,
  PRIMARY KEY (`VKEY`),
  KEY `PZN` (`PZN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `bnkbase`.`tb_real` (
  `VKEY` char(4) NOT NULL,
  `REAL` char(4) DEFAULT NULL,
  `NAME_OGR` char(60) DEFAULT NULL,
  PRIMARY KEY (`VKEY`),
  KEY `REAL` (`REAL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `bnkbase`.`tb_rgn` (
  `VKEY` char(2) NOT NULL,
  `RGN` char(2) NOT NULL,
  `NAME` char(40) DEFAULT NULL,
  `CENTER` char(30) DEFAULT NULL,
  `NAMET` char(40) DEFAULT NULL,
  PRIMARY KEY (`VKEY`),
  KEY `RGN` (`RGN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `bnkbase`.`tb_tnp` (
  `VKEY` char(2) NOT NULL,
  `TNP` char(2) DEFAULT NULL,
  `FULLNAME` char(25) DEFAULT NULL,
  `SHORTNAME` char(5) DEFAULT NULL,
  PRIMARY KEY (`VKEY`),
  KEY `TNP` (`TNP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `bnkbase`.`tb_uer` (
  `VKEY` char(2) NOT NULL,           
  `UER` char(1) NOT NULL,
  `UERNAME` char(70) DEFAULT NULL,
  PRIMARY KEY (`VKEY`),
  KEY `UER` (`UER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `bnkbase`.`bnkseek` (
  `REAL` char(4) DEFAULT NULL,
  `PZN` char(2) DEFAULT NULL,
  `UER` char(1) NOT NULL,
  `RGN` char(2) NOT NULL,
  `IND` char(6) DEFAULT NULL,
  `TNP` char(1) DEFAULT NULL,
  `NNP` char(25) DEFAULT NULL,
  `ADR` char(30) DEFAULT NULL,
  `RKC` char(9) DEFAULT NULL,
  `NAMEP` char(45) NOT NULL,
  `NEWNUM` char(9) NOT NULL,
  `TELEF` char(25) DEFAULT NULL,
  `REGN` char(9) DEFAULT NULL,
  `OKPO` char(8) DEFAULT NULL,
  `DT_IZM` date NOT NULL,
  `KSNP` char(20) DEFAULT NULL,
  `DATE_IN` date NOT NULL,
  `DATE_CH` date DEFAULT NULL,
  PRIMARY KEY (`NEWNUM`),
  UNIQUE KEY `NEWNUM_UNIQUE` (`NEWNUM`),
  KEY `FK_RGN_idx` (`RGN`),
  KEY `FK_REAL_idx` (`REAL`),
  KEY `FK_PZN_idx` (`PZN`),
  KEY `FK_TNP_idx` (`TNP`),
  KEY `FK_UER_idx` (`UER`),
  CONSTRAINT `FK_PZN` FOREIGN KEY (`PZN`) REFERENCES `tb_pzn` (`PZN`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_REAL` FOREIGN KEY (`REAL`) REFERENCES `tb_real` (`REAL`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_RGN` FOREIGN KEY (`RGN`) REFERENCES `tb_rgn` (`RGN`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_TNP` FOREIGN KEY (`TNP`) REFERENCES `tb_tnp` (`TNP`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_UER` FOREIGN KEY (`UER`) REFERENCES `tb_uer` (`UER`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;